repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.6
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi, jupyter ]
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1 # Use the latest stable version
  hooks:
  - id: mypy
    args: [ "--ignore-missing-imports" ] # Optional args, adjust as needed
    additional_dependencies: [ types-PyYAML ]

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1 # Use the latest stable version
  hooks:
  - id: nbstripout
    files: \.ipynb$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0 # Use the latest stable version
  hooks:
  - id: check-ast
  - id: trailing-whitespace

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [ --py3-plus ]
